import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

// Configure the OpenAI API client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(req: NextRequest) {
  try {
    const { imageBase64 } = await req.json();

    if (!imageBase64) {
      return NextResponse.json(
        { error: "Image base64 is required" },
        { status: 400 }
      );
    }

    const prompt = `Analyze the following image in base64 format. Describe the image in a single, engaging sentence that includes:
    - The product type (e.g., utensils, clothing)
    - The color (e.g., silver, blue)
    - The quantity (e.g., two forks, one spoon).
    Keep it natural, clear, and concise without being overly detailed.`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4-turbo",
      messages: [
        { role: "system", content: "You are a helpful assistant." },
        {
          role: "user",
          content: [
            { type: "text", text: `${prompt}` },
            {
              type: "image_url",
              image_url: {
                url: imageBase64,
              },
            },
          ],
        },
      ],
      max_tokens: 60,
    });

    const description = completion.choices[0]?.message?.content?.trim();
    console.log("Generated Description:", description);

    if (!description) {
      return NextResponse.json(
        { error: "No description generated by GPT" },
        { status: 500 }
      );
    }

    return NextResponse.json({ description });
  } catch (error) {
    console.error("Error generating description with GPT:", error);
    return NextResponse.json(
      { error: "Error generating description" },
      { status: 500 }
    );
  }
}
